store/orders/urls.py
from django.urls import path

from orders.views import (CancelTemplateView, OrderCreateView, OrderDetailView,
                          OrderListView, SuccessTemplateView)

app_name = 'orders'
urlpatterns = [
    path('order-create', OrderCreateView.as_view(), name='order_create'),
    path('order-success', SuccessTemplateView.as_view(), name='order_success'),
    path('order-cancel', CancelTemplateView.as_view(), name='order_cancel'),
    path('', OrderListView.as_view(), name='order_list'),
    path('order/<int:pk>', OrderDetailView.as_view(), name='order'),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/orders/models.py
from collections import namedtuple

from django.db import models

from products.models import Basket
from users.models import User


class Order(models.Model):
    status = namedtuple('Status', ['code', 'name'])
    CREATED, PAID, ON_WAY, DELIVERED = 0, 1, 2, 3
    STATUS = (
        status(CREATED, 'Создан'),
        status(PAID, 'Оплачен'),
        status(ON_WAY, 'В пути'),
        status(DELIVERED, 'Доставлен')
    )

    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=256)
    address = models.CharField(max_length=256)

    created = models.DateTimeField(auto_now_add=True)
    basket_history = models.JSONField(default=dict)
    status = models.SmallIntegerField(default=CREATED, choices=STATUS)

    def __str__(self):
        return f'{self.id}, {self.last_name}, {self.first_name}'

    def update_after_payment(self):
        basket = Basket.objects.filter(user=self.initiator)
        self.status = self.PAID
        self.basket_history = {
            'purchased_items': [item.save_to_history() for item in basket],
            'total_sum': float(basket.total_sum())
        }
        basket.delete()
        self.save()

store/orders/forms.py
from django import forms

from orders.models import Order


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Иван'}
    ))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Иванов'}
    ))
    email = forms.CharField(widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'you@example.com'}
    ))
    address = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Россия, Москва, ул. Мира, дом 6'}
    ))

    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address')

store/orders/views.py
from http import HTTPStatus

import stripe
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from common.views import TitleMixin
from orders.forms import OrderForm
from orders.models import Order
from products.models import Basket

stripe.api_key = settings.STRIPE_SECRET


class OrderCreateView(TitleMixin, CreateView):
    template_name = 'orders/order_create.html'
    title = 'StoreMust - Оформление заказа'
    form_class = OrderForm
    success_url = reverse_lazy('orders:order_create')

    def post(self, request, *args, **kwargs):
        super(OrderCreateView, self).post(self, request, *args, **kwargs)
        basket = Basket.objects.filter(user=self.request.user)
        checkout_session = stripe.checkout.Session.create(
            line_items=basket.stripe_products(),
            metadata={'order_id': self.object.id},
            mode='payment',
            success_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:order_success')),
            cancel_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:order_cancel'))
        )
        return HttpResponseRedirect(checkout_session.url, HTTPStatus.SEE_OTHER)

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        return super(OrderCreateView, self).form_valid(form)


class SuccessTemplateView(TitleMixin, TemplateView):
    template_name = 'orders/success.html'
    title = 'StoreMust - Спасибо за заказ!'


class CancelTemplateView(TemplateView):
    template_name = 'orders/cancel.html'
    title = 'StoreMust - Заказ не был оплачен :('


@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError:
        # Invalid signature
        return HttpResponse(status=400)

    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        # Retrieve the session. If you require line items in the response, you may include them by expanding line_items.
        session = event['data']['object']
        fulfill_order(session)

    # Passed signature verification
    return HttpResponse(status=200)


def fulfill_order(session):
    order_id = int(session.metadata.order_id)
    order = Order.objects.get(id=order_id)
    order.update_after_payment()


class OrderListView(TitleMixin, ListView):
    template_name = 'orders/orders.html'
    title = 'StoreMust - Заказы'
    queryset = Order.objects.all()
    ordering = '-created'

    def get_queryset(self):
        queryset = super(OrderListView, self).get_queryset()
        return queryset.filter(initiator=self.request.user)


class OrderDetailView(DetailView):
    template_name = 'orders/order.html'
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderDetailView, self).get_context_data()
        context['title'] = f'StoreMust - Заказ №{self.object.id}'
        return context

store/orders/templates/orders/cancel.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="card-header">
        <h3 class="text-center font-weight-light my-4">Отмена оплаты</h3>
    </div>
    <div class="card-body text-center">
        <h4>Ваш заказ не оплачен, возращайтесь скорее!</h4>
    </div>
{% endblock %}

store/orders/templates/orders/order.html
{% extends 'products/base.html' %}
{% load static %}
{% load humanize %}

{% block css %}
    <link href="{% static 'vendor/css/orders.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
  <section>
      <div class="container pt-5">
          <div class="text-center mt-5">
              <h1>Заказ №{{ object.id }}</h1>
              <div class="orders mt-5">
                  <table class="table">
                      <thead>
                      <tr>
                          <th scope="col">Название</th>
                          <th scope="col">Кол-во</th>
                          <th scope="col">Цена</th>
                          <th scope="col">Сумма</th>
                      </tr>
                      </thead>
                      <tbody>
                      {% for item in object.basket_history.purchased_items %}
                          <tr>
                              <th scope="row">
                                  {{ item.product_name }}
                              </th>
                              <td>{{ item.quantity }}</td>
                              <td>{{ item.price |intcomma }} руб.</td>
                              <td>{{ item.sum | intcomma }} руб.</td>
                          </tr>
                      {% endfor %}
                      </tbody>
                  </table>
                  <p class="float-right h4 mt-3">Итого {{ object.basket_history.total_sum | intcomma }} руб.</p>
              </div>
          </div>
      </div>
  </section>
{% endblock %}

store/orders/templates/orders/order_create.html
{% extends 'products/base.html' %}
{% load static %}
{% load humanize %}

{% block css %}
    <link href="{% static 'vendor/css/orders.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <div class="alert alert-warning text-center" role="alert">
            Пожалуйста, заполните адрес электронной почты.
        </div>
        <div class="container">
            <div class="py-5 text-center">
                <h1>Оформление заказа</h1>
            </div>
            <div class="row g-5">
                <div class="col-md-5 col-lg-4 order-md-last">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-primary">Корзина</span>
                        <span class="badge badge-primary badge-pill text-white">{{ basket.total_quantity }}</span>
                    </h4>
                    <ul class="list-group mb-3">
                        {% for item in basket %}
                            <li class="list-group-item d-flex justify-content-between lh-sm">
                                <div>
                                    <h6 class="my-0">{{ item.product.name }}</h6>
                                    <small class="text-muted">{{ item.quantity }} шт.</small>
                                </div>
                                <span class="text-muted">{{ item.sum | intcomma }}руб.</span>
                            </li>
                        {% endfor %}
                        <li class="list-group-item d-flex justify-content-between">
                            <span>Сумма к оплате</span>
                            <strong>{{ basket.total_sum | intcomma }}.</strong>
                        </li>
                    </ul>
                </div>
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Адрес доставки</h4>
                    <form action="{% url 'orders:order_create' %}" method="post">
                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-sm-6">
                                <label for="{{ form.first_name.id_for_label }}">Имя</label>
                                    {{ form.first_name }}
                            </div>

                            <div class="col-sm-6">
                                <label for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                    {{ form.last_name }}
                            </div>

                            <div class="col-12 mt-3">
                                <label for="{{ form.email.id_for_label }}">Адрес электронной почты</label>
                                    {{ form.email }}
                            </div>

                            <div class="col-12 mt-3">
                                <label for="{{ form.address.id_for_label }}">Адрес</label>
                                    {{ form.address }}
                            </div>

                        </div>

                        <hr class="my-4">

                        <button class="w-100 btn btn-primary btn-lg" type="submit">Продолжить</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

store/orders/templates/orders/orders.html
{% extends 'products/base.html' %}
{% load static %}
{% load humanize %}

{% block css %}
    <link href="{% static 'vendor/css/orders.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
  <section>
      <div class="container pt-5">
          <div class="text-center mt-5">
              <h1>Заказы</h1>
              <div class="orders mt-5">
                  <table class="table">
                      <thead>
                      <tr class="table-light">
                          <th scope="col">#</th>
                          <th scope="col">Статус</th>
                          <th scope="col">Создан</th>
                          <th scope="col">Итого</th>
                          <th scope="col">Действие</th>
                      </tr>
                      </thead>
                      <tbody>
                      {% for order in object_list %}
                          <tr>
                              <th scope="row">{{ order.id }}</th>
                              <td>{{ order.get_status_display }}</td>
                              <td>{{ order.created | naturalday }}</td>
                              <td>{{ order.basket_history.total_sum | intcomma }} руб.</td>
                              <td>
                                  <a href="{% url 'orders:order' order.id %}">просмотреть</a>
                              </td>
                          </tr>
                      {% endfor %}
                      </tbody>
                  </table>
              </div>
          </div>
      </div>
  </section>
{% endblock %}

store/orders/templates/orders/success.html
{% extends 'users/base.html' %}

{% block title %}
<title>StorMust - Спасибо за заказ!</title>
{% endblock %}

{% block content %}
    <div class="card-header">
        <h3 class="text-center font-weight-light my-4">Спасибо за заказ!</h3>
    </div>
    <div class="card-body text-center">
        <h4>Ваш заказ успешно сформирован.</h4>
    </div>
{% endblock %}